### ISSUE TITLE
csi对接k8s无法使用

### ISSUE THREAD

**Issue by mjhalxx** [opencurve/curve-csi#18]
使用 curve-operator 部署了 curvebs  
参照部署指引，使用 helm chart 部署 curve-csi 使用的镜像是 curve-csi:v3.0.0  
配置 storageclasss:
```yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: curve
parameters:
  user: k8s
  cloneLazy: "true"
provisioner: curve.csi.netease.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
创建 PVC :
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: curve-test-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: curve
```
 csi-curveplugin 报错如下:  
``` 
[controllerserver.go:91] "ID: 33 Req-ID: pvc-e27a23xxxxx failed to get volDetail" err="can not run curve [stat --user k8s --filename /k8s/csi-vol-pvc-e27a23xxxxx],err: exit status 1, output: stat fail, ret = -2 FAILED"
```
